[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
included-patches = "'Hide ads' 'Disable analytics' 'Remove build expired popup' 'Sanitize sharing links'"
exclusive-patches = true

[Messenger]
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"

[Photos]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/google-photos-7-64-0-873168826-release/google-photos-7-64-0-873168826-11-android-apk-download/"
arch = "both"
included-patches = "'Enable DCIM folders backup control'"

