enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config
[Instagram]
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-418-0-0-29-77-release/"
included-patches = "'Anonymous story viewing' 'Hide Stories from Home' 'Hide suggested content' 'Enable developer menu' 'Change link sharing domain' 'Disable signature check' 'Disable story auto flipping'"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"

[Photos]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/google-photos-7-64-0-873168826-release/google-photos-7-64-0-873168826-11-android-apk-download/"
included-patches = "'Enable DCIM folders backup control'"
